name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
         username: ${{ secrets.USER  }}
         password: ${{ secrets.PASSWORD }}

         - name: Build and push Docker images
           uses: docker/build-push-action@v6.0.1
           with:
             context: .
             file: .
             push: true
             tags: |
               ssatangoss/dcodesxwv:v1
         
      
    
