name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Docker Login
        uses: docker/login-action@2.1.0
        with:
         username: ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         
      - name: constucao imagem Docker3.2.0
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ssatangoss/dcodesxwv:v1
            ssatangoss/dcodesxwv:latest     

  
